master:
  services:
    - juice-shop

teams:
  - name: players
    size: 1
    roles:
      - name: player
        see:
          - master

services:
  - name: juice-shop
    port: 3000

  - name: rootthebox
    port: 3000
