version: '3'
services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_USER: ctfd
      MYSQL_PASSWORD: ctfd
      MYSQL_ROOT_USER: ctfd
      MYSQL_ROOT_PASSWORD: ctfd
      MYSQL_DATABASE: ctfd
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  copas:
    image: copas:latest
    ports:
      - "8000:8000"
    volumes:
      - /home/simon/Documents/bc/copas/games/owasp_juice_shop/config.yml:/app/config.yml
    environment:
      ROLE: master

  ctfd:
    image: ctfd/ctfd
    depends_on:
      - mariadb
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: mysql+pymysql://ctfd:ctfd@mariadb:3306/ctfd

volumes:
  db_data:
    driver: local
